### ISSUE TITLE
Question: how to enable ccache in SkiffOS

### ISSUE THREAD

**Issue by ohadln** [paralin/SkiffOS#33]
As I seem to make many buildroot compilation - sometimes including 'make clean' - I wonder how can I enable buildroot's ccache under SkiffOS to reduce compilation time.

Thanks,
Ohad

**Comment by paralin** [comment]
Cache is already enabled on default under ~/.buildroot-ccache

You can tweak this by overriding the Buildroot compiler cache settings in your own config package. 

I will add more docs on exploring the Buildroot config today.
