### ISSUE TITLE
new arch: docker on mips architecture with skiffos

### ISSUE THREAD

**Issue by phamvancam2104** [paralin/SkiffOS#62]
Can we build SkiffOS with docker daemon for MIPS architecture?

**Comment by paralin** [comment]
Yes you can. Which board are you attempting to use? We can try to get you set up.

**Comment by phamvancam2104** [comment]
I do not have a specific board but, in general, the board has around 120->150 RAM and I want to run the docker on a Linux operating system. Can we do that?

**Comment by paralin** [comment]
@phamvancam2104 Yes Skiff will theoretically work on any system that can run Linux.

**Comment by phamvancam2104** [comment]
@paralin thank you very much for your answer, I want to run the skiffOS with docker daemon on my device because I want to use the computing resource of my devices (around 10k->100k devices) to run other applications built by others. So that's why I think about using a small Linux OS, like SkiffOS, with built-in docker daemon. By this way, my device can create containers for applications built in terms of docker images. The applications can be climate predictions or data analytics. Can you tell me which steps should I follow to build this skiffOS for MIPS?

**Comment by paralin** [comment]
@phamvancam2104 Look at the boards under configs/pi/3 or configs/odroid/xu4 and configs/pi/common to get an understanding of how to add a new architecture / board to Skiff.

Your approach is a good idea, and actually the original intended purpose of Skiff (making it easy to run containerized apps on various embedded platforms).

**Comment by phamvancam2104** [comment]
@paralin I tried to build the SkiffOS for rpi1 and got the following errors

> `package/pkg-generic.mk:167: recipe for target '/home/campv/Documents/SkiffOS/workspaces/default/build/host-gcc-initial-6.4.0/.stamp_extracted' failed
make[3]: *** [/home/campv/Documents/SkiffOS/workspaces/default/build/host-gcc-initial-6.4.0/.stamp_extracted] Error 2
Makefile:16: recipe for target '_all' failed
make[2]: *** [_all] Error 2
make[2]: Leaving directory '/home/campv/Documents/SkiffOS/workspaces/default'
Makefile:52: recipe for target 'compile' failed
make[1]: *** [compile] Error 2
make[1]: Leaving directory '/home/campv/Documents/SkiffOS/build'
Makefile:2: recipe for target 'compile' failed
make: *** [compile] Error 2`

Can you tell me where is the problem (note that I did not make any modification to the code cloned from git)?

**Comment by paralin** [comment]
Well you didn't paste the actual error. You just pasted the makefile errors. And judging by the log, it's probably related to your toolchain settings. 

I haven't tested the pi1 at all, notice that it's marked as experimental.

**Comment by paralin** [comment]
Please try this:

```
git clone https://github.com/paralin/SkiffOS.git skiffos-mips
cd skiffos-mips
git checkout next
SKIFF_CONFIG=pi/1 make configure compile
```

And let me know if it works?

**Comment by phamvancam2104** [comment]
Hi @paralin 
I'll try it now, but are we building skiffOS for mips or pi/1 in this case?
Cam,

**Comment by paralin** [comment]
I'm replying to your comment saying that you attempted to build pi1 and it didn't work. 

The mips question requires knowing what hardware you want to use.
